### ISSUE TITLE
g++ -std=c++11 -Wall -c IMEI-AndroidChanger.cpp -o IMEI-AndroidChanger.o ?

### ISSUE THREAD

**Issue by feiser2016** [Untouchable17/Android-IMEI-Changer#2]
g++ -std=c++11 -Wall -c IMEI-AndroidChanger.cpp -o IMEI-AndroidChanger.o ?

~/Android-IMEI-Changer $ file IMEI-AndroidChanger.o
IMEI-AndroidChanger.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), not stripped

Should I use the following command?
g++ -std=c++11 -Wall IMEI-AndroidChanger.cpp -o IMEI-AndroidChanger

~/Android-IMEI-Changer $ file IMEI-AndroidChanger
IMEI-AndroidChanger: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, not stripped

~/Android-IMEI-Changer $ ldd IMEI-AndroidChanger
        libc++_shared.so => /data/data/com.termux/files/usr/lib/libc++_shared.so
        libdl.so => /system/lib64/libdl.so
        libm.so => /system/lib64/libm.so
        libc.so => /system/lib64/libc.so
        ld-android.so => /system/lib64/ld-android.so

How can i package IMEI-AndroidChanger and the so library to other phone?

**Comment by Untouchable17** [comment]
Move or copy the IMEI-AndroidChanger executable to the bin directory and the libc++_shared.so library to the lib directory. I  mean:

```
/app
├── bin
│   └── IMEI-AndroidChanger
└── lib
    └── libc++_shared.so
```
Create a zip archive of the directory structure and transfer to other phone

**Comment by ma232-cell** [comment]
How to change imei

**Comment by AdilAli026** [comment]
When I moved IMEI Changer executable and libshared++.so into the apps(kalinethunter) bin and lib
It still says line99:invalid argument
My guess is the the program is not well written so I can't ever work

**Comment by shrikantkumar53139-maker** [comment]
/app
├── bin
│   └── IMEI-AndroidChanger
└── lib
    └── libc++_shared.so
