### ISSUE TITLE
unable to compile on Android using the guide.

### ISSUE THREAD

**Issue by Andromodgod** [Untouchable17/Android-IMEI-Changer#3]
Get the Following error when running the command on termux on Android 14.
![Screenshot_20240505-232508_Termux](https://github.com/Untouchable17/Android-IMEI-Changer/assets/5508595/793b2abf-10b8-4b92-bf56-2e401f14654d)

`javac -cp ".:$ANDROID_HOME/platforms/android-11/android.jar" ImeiManager.java Main.java`

`error: file not found: ImeiManager.java
Usage: javac <options> <source files>
use --help for a list of possible options`

Kindly advice.

**Comment by NatLoki** [comment]
Were you able to change the IMEI on android 14?

**Comment by VR3K** [comment]
I have this same problem, Android 13

**Comment by Untouchable17** [comment]
> Get the Following error when running the command on termux on Android 14. ![Screenshot_20240505-232508_Termux](https://private-user-images.githubusercontent.com/5508595/328039912-793b2abf-10b8-4b92-bf56-2e401f14654d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDIyNTMsIm5iZiI6MTcyMTQwMTk1MywicGF0aCI6Ii81NTA4NTk1LzMyODAzOTkxMi03OTNiMmFiZi0xMGI4LTRiOTItYmY1Ni0yZTQwMWYxNDY1NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMTUxMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjczOTMxZmU0Y2Q0ZGQ3MjNlOWRlYWQ2ZGJiNmEyOWExZTE2YjY3NTg2NjQyMDdhYzM0MWM1ZWYzNTIwM2ZhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.33kRO0B8bGdD8rJvAPtlIZ6_XnbcWdH-Kzfp6HI0Hjw)
> 
> `javac -cp ".:$ANDROID_HOME/platforms/android-11/android.jar" ImeiManager.java Main.java`
> 
> `error: file not found: ImeiManager.java Usage: javac <options> <source files> use --help for a list of possible options`
> 
> Kindly advice.

Use ANDRAX/NETHUNTER with CUSTOM kernel and firmware

**Comment by Untouchable17** [comment]
The file you are trying to execute is not compatible with your operating system architecture. Your phone has a stock kernel, but requires a custom kernel to run. Find a flashed kernel with firmware for your device, install ANDRAX/NetHunter or work as root on Termux and everything will work
