### ISSUE TITLE
line 99

### ISSUE THREAD

**Issue by SaaHSx4** [Untouchable17/Android-IMEI-Changer#4]
Running the progress...
./install.sh:  line 99: ./IMEI-AndroidChanger.o Invalid argument

Where is the problem ?

**Comment by VR3K** [comment]
same 
 ./install.sh: line 99: ./IMEI-AndroidChanger.o Invalid argument

**Comment by lmtzsn** [comment]
same here

**Comment by Untouchable17** [comment]
The file you are trying to execute is not compatible with your operating system architecture. Your phone has a stock kernel, but requires a custom kernel to run. Find a flashed kernel with firmware for your device, install ANDRAX/NetHunter or work as root on Termux and everything will work
