### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by iconium21** [Untouchable17/Android-IMEI-Changer#5]
On running `sudo ./install.sh`
I get this error:

`./install.sh: line 99: ./IMEI-AndroidChanger.o: cannot execute binary file: Exec format error`

**Comment by Untouchable17** [comment]
The file you are trying to execute is not compatible with your operating system architecture. Your phone has a stock kernel, but requires a custom kernel to run. Find a flashed kernel with firmware for your device, install ANDRAX/NetHunter or work as root on Termux and everything will work

**Comment by chaudary133** [comment]
Unable to run the file 

<img width="949" height="1079" alt="Image" src="https://github.com/user-attachments/assets/b8ad1edb-3a62-4a71-a204-d171dea3037b" />
